Repository s-soldesk/HRM-Project, pull requests merged in 2025-02, with the labels that each got.

#7 Fix/security auth admin
  src/main/java/com/hrm/config/SecurityConfig.java
  src/main/resources/mapper/UserAccountMapper.xml
  src/main/resources/templates/layout/sidebar.html
Labels: bug

#12 Fix: 사원관리 페이지 사이드바 수정
  src/main/resources/static/css/employee.css
  src/main/resources/templates/employee/index.html
Labels: UI/UX

#13 명확한 Bossam
  src/main/java/com/hrm/controller/ScheduleController.java
  src/main/java/com/hrm/dto/ScheduleDto.java
  src/main/resources/static/js/calenderUI.js
Labels: bug

#18 사용자 로그인정보 추가
  src/main/java/com/hrm/dao/UserAccountDao.java
  src/main/java/com/hrm/dto/EmployeeDto.java
  src/main/java/com/hrm/dto/UserAccountDto.java
  src/main/java/com/hrm/enums/Position.java
  src/main/java/com/hrm/enums/Role.java
  src/main/java/com/hrm/service/EmployeeService.java
  src/main/resources/static/js/components/table.js
  src/main/resources/templates/employee/index.html
Labels: feature

#45 사원검색 오류 수정
  src/main/java/com/hrm/controller/EmployeeManagementController.java
  src/main/resources/templates/employee/index.html
Labels: bug
